### ISSUE TITLE
Overall task tracker

### ISSUE THREAD

**Issue by rrrrando** [rrrrando/budgetcalc#8]
- [x] Set up Github #1
- [x] Set up Figma #2
- [x] Set up production env. #3
- [x] Set up Slack #4
- [x] Set up dev env. #5
- [x] Mobile design #6
- [ ] Desktop design #7
- [x] Code design system
- [x] Code Javascript logic
- [x] Code HTML
